version: '3.6'
services:
  mysql:
    image: mysql:8.0.32
    volumes:
      - ./docker/data/mysql/data:/var/lib/mysql
      - ./docker/mysql:/etc/mysql/conf.d
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_USER=app"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_DATABASE=app"
    ports:
      - "33061:3306"

  python:
    build:
      context: ./
      dockerfile: ./docker/python/Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      - "MYSQL_HOST=mysql"
      - "MYSQL_USER=app"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_DATABASE=app"
    tty:
        true

